#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

postgres_ready(){
python << END
import sys
import psycopg2
try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${PG_HOST}",
        port="${PG_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
>&2 echo "Waiting for PostgreSQL to become available....:-("
sleep 1
done
>&2 echo "PostgreSQL is ready!!!!...:-)"
python3 manage.py createsuperuser --noinput || true
psql -d ${POSTGRES_DB} -c "INSERT INTO public.properties_property(title, ref_code, description, country, city,user_id) VALUES ('test1', 'code', 'desc', 'AU','Sydney','1');" || true

exec "$@"
